# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4c42ae23f4d8d0cb6bfcec86ad3b1472e10c90f49443b51abac28bff0fac68b8fc5442e7b6472721a6369edbe6892f08aeafbf70c73af7be91832c2adc175e4

test:
  secret_key_base: a197d6719b5732828313f4fd3281a7c9bf57a2c278bdd1d29aee5c05553688ef241999e805257fef8bf19ada90c27adf1470c91a575778544d8f1a7fd90aa30a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
